{
 "title": "hBlock Resolver metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Total answers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(answer_total[$__range]))"
    }
   ]
  },
  {
   "title": "Blocked answers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(answer_blocked[$__range]))"
    }
   ]
  },
  {
   "title": "Blocked answers (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(answer_blocked[$__range])) / sum(increase(answer_total[$__range]))"
    }
   ]
  },
  {
   "title": "Request sources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(request_internal[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "Internal"
    },
    {
     "expr": "sum(irate(request_udp[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(irate(request_tcp[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(irate(request_dot[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "DoT"
    },
    {
     "expr": "sum(irate(request_doh[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "DoH"
    },
    {
     "expr": "sum(irate(request_xdp[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "XDP"
    }
   ]
  },
  {
   "title": "Cached/Uncached answers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(answer_cached[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "Cached"
    },
    {
     "expr": "sum(irate(answer_total[$__rate_interval]) * $__interval_ms / 1000) - sum(irate(answer_cached[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "Uncached"
    }
   ]
  },
  {
   "title": "Answer RCODEs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(answer_noerror[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "NOERROR"
    },
    {
     "expr": "sum(irate(answer_nodata[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "NODATA"
    },
    {
     "expr": "sum(irate(answer_nxdomain[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "NXDOMAIN"
    },
    {
     "expr": "sum(irate(answer_servfail[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "SERVFAIL"
    }
   ]
  },
  {
   "title": "Answer latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(latency_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}