# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: "hblock-resolver"

# https://hub.docker.com/_/traefik
x-traefik-image: &traefik-image "docker.io/traefik:3.0"
# https://hub.docker.com/r/hectorm/hblock-resolver
x-hblock-resolver-image: &hblock-resolver-image "docker.io/hectorm/hblock-resolver:latest"
# https://hub.docker.com/r/grafana/grafana
x-grafana-image: &grafana-image "docker.io/grafana/grafana:10.3.1"
# https://hub.docker.com/r/prom/prometheus
x-prometheus-image: &prometheus-image "docker.io/prom/prometheus:v2.49.1"

services:

  traefik:
    image: *traefik-image
    restart: "on-failure:3"
    hostname: "traefik"
    networks:
      - "hblock-resolver"
    ports:
      - "80:80/tcp" # HTTP.
      - "443:443/tcp" # HTTPS.
      - "443:443/udp" # HTTPS (QUIC).
      - "853:853/tcp" # DNS over TLS.
    volumes:
      - "./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./config/traefik/dynamic/:/etc/traefik/dynamic/:ro"
      - "traefik-acme:/etc/traefik/acme/"
    environment:
      TRAEFIK_BASIC_AUTH: "${TRAEFIK_BASIC_AUTH:-}"
      TRAEFIK_TLS_RESOLVER: "${TRAEFIK_TLS_RESOLVER:-}"
      DOMAIN: "${DOMAIN:?}"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      start_period: "60s"
      interval: "10s"
      timeout: "5s"
      retries: 2

  hblock-resolver:
    image: *hblock-resolver-image
    restart: "on-failure:3"
    hostname: "hblock-resolver"
    networks:
      - "hblock-resolver"
    ports:
      - "127.0.0.153:53:53/udp" # DNS over UDP.
      - "127.0.0.153:53:53/tcp" # DNS over TCP.
    volumes:
      - "hblock-resolver-data:/var/lib/knot-resolver/"
    environment:
      KRESD_INSTANCE_NUMBER: "${KRESD_INSTANCE_NUMBER:-4}"

  grafana:
    image: *grafana-image
    restart: "on-failure:3"
    hostname: "grafana"
    networks:
      - "hblock-resolver"
    volumes:
      - "./config/grafana/provisioning/:/etc/grafana/provisioning/:ro"
      - "grafana-data:/var/lib/grafana/"
    environment:
      GF_SERVER_ROOT_URL: "https://${DOMAIN:?}/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD:?}"
      GF_SECURITY_SECRET_KEY: "${GRAFANA_SECRET_KEY:?}"
      GF_SECURITY_COOKIE_SECURE: "true"
      GF_SECURITY_DISABLE_GRAVATAR: "true"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
      GF_AUTH_BASIC_ENABLED: "false"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:3000/api/health"]
      start_period: "60s"
      interval: "10s"
      timeout: "5s"
      retries: 2

  prometheus:
    image: *prometheus-image
    restart: "on-failure:3"
    hostname: "prometheus"
    networks:
      - "hblock-resolver"
    volumes:
      - "./config/prometheus/:/etc/prometheus/:ro"
      - "prometheus-data:/prometheus/"
    command:
      - "--web.external-url=https://${DOMAIN:?}/prometheus/"
      - "--web.route-prefix=/prometheus/"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus/"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries/"
      - "--web.console.templates=/usr/share/prometheus/consoles/"
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:9090/prometheus/-/healthy"]
      start_period: "60s"
      interval: "10s"
      timeout: "5s"
      retries: 2

volumes:

  traefik-acme:

  hblock-resolver-data:

  grafana-data:

  prometheus-data:

networks:

  hblock-resolver:
