global:
  scrape_interval: "15s"
  scrape_timeout: "15s"

scrape_configs:
  - job_name: "hblock-resolver"
    metrics_path: "/metrics"
    scheme: "https"
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["hblock-resolver:8453"]
