#!/bin/sh
# shellcheck disable=SC2034

if [ ! -e "${KRESD_DATA_DIR:?}"/hblock/ ]; then
	mkdir -p "${KRESD_DATA_DIR:?}"/hblock/
fi

HBLOCK_OUTPUT_FILE="${KRESD_DATA_DIR:?}"/hblock/blocklist.rpz

if [ -e "${KRESD_DATA_DIR:?}"/hblock/sources.list ]; then
	HBLOCK_SOURCES_FILE="${KRESD_DATA_DIR:?}"/hblock/sources.list
fi

if [ -e "${KRESD_DATA_DIR:?}"/hblock/allow.list ]; then
	HBLOCK_ALLOWLIST_FILE="${KRESD_DATA_DIR:?}"/hblock/allow.list
fi

if [ -e "${KRESD_DATA_DIR:?}"/hblock/deny.list ]; then
	HBLOCK_DENYLIST_FILE="${KRESD_DATA_DIR:?}"/hblock/deny.list
fi

HBLOCK_REDIRECTION='.'
HBLOCK_TEMPLATE='%D CNAME %R\n*.%D CNAME %R'
HBLOCK_COMMENT=';'
HBLOCK_FILTER_SUBDOMAINS='true'
