{
 "title": "hBlock Resolver metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total answers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(answer_total[$__range]))"
    }
   ]
  },
  {
   "title": "Blocked answers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(answer_blocked[$__range]))"
    }
   ]
  },
  {
   "title": "Blocked answers (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(answer_blocked[$__range])) / sum(increase(answer_total[$__range]))"
    }
   ]
  },
  {
   "title": "Request sources",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(request_internal[$__range]))",
     "legendFormat": "Internal"
    },
    {
     "expr": "sum(idelta(request_udp[$__range]))",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(idelta(request_tcp[$__range]))",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(idelta(request_dot[$__range]))",
     "legendFormat": "DoT"
    },
    {
     "expr": "sum(idelta(request_doh[$__range]))",
     "legendFormat": "DoH"
    },
    {
     "expr": "sum(idelta(request_xdp[$__range]))",
     "legendFormat": "XDP"
    }
   ]
  },
  {
   "title": "Cached/Uncached answers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(answer_cached[$__range]))",
     "legendFormat": "Cached"
    },
    {
     "expr": "sum(idelta(answer_total[$__range])) - sum(idelta(answer_cached[$__range]))",
     "legendFormat": "Uncached"
    }
   ]
  },
  {
   "title": "Answer RCODEs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(answer_noerror[$__range]))",
     "legendFormat": "NOERROR"
    },
    {
     "expr": "sum(idelta(answer_nodata[$__range]))",
     "legendFormat": "NODATA"
    },
    {
     "expr": "sum(idelta(answer_nxdomain[$__range]))",
     "legendFormat": "NXDOMAIN"
    },
    {
     "expr": "sum(idelta(answer_servfail[$__range]))",
     "legendFormat": "SERVFAIL"
    }
   ]
  },
  {
   "title": "Answer latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(latency_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}