#!/bin/sh

set -eu

# Dump environment variables
export-env > /etc/profile.d/container-environment.sh

# Generate self-signed certificate if it does not exist
if [ ! -f '/var/lib/knot-resolver/ssl/server.key' ]; then
	su -c renew-self-signed-cert - knot-resolver
fi

# Download blacklist zone if it does not exist
if [ ! -f '/var/lib/knot-resolver/hblock.rpz' ]; then
	su -c update-blacklist-rpz - knot-resolver
fi

# Download GeoIP database if it does not exist
if [ ! -f '/var/lib/knot-resolver/geoip.mmdb' ]; then
	su -c update-geoip-database - knot-resolver
fi

# Run supervisor
exec supervisord -c /etc/supervisord.conf
