#!/bin/sh

set -eu

# Generate self-signed certificate if it does not exist
if [ ! -f '/var/lib/knot-resolver/ssl/self.key' ]; then
	printf '%s\n' 'Generating self-signed certificate...'
	renew-self-signed-cert
fi

# Download blacklist zone if it does not exist
if [ ! -f '/var/lib/knot-resolver/blacklist.rpz' ]; then
	printf '%s\n' 'Downloading blacklist zone...'
	update-blacklist-rpz
fi

# Download GeoIP database if it does not exist
if [ ! -f '/var/lib/knot-resolver/geoip.mmdb' ]; then
	printf '%s\n' 'Downloading GeoIP database...'
	update-geoip-database
fi

exec supervisord -c /etc/supervisord.conf
