#!/bin/sh

set -eu

CERT_DIR='/var/lib/knot-resolver/ssl/'
MUST_RESTART_KRESD=false

if [ ! -d "${CERT_DIR}" ]; then
	mkdir -p "${CERT_DIR}"
fi

# Generate private key if it does not exist
if [ ! -f "${CERT_DIR}"/self.key ]; then
	MUST_RESTART_KRESD=true
	(cd "${CERT_DIR}" \
		&& rm -f self.key self.csr self.crt \
		&& openssl ecparam -genkey -name prime256v1 -out self.key \
		&& chown root:knot-resolver self.key \
		&& chmod 640 self.key \
	)
fi

# Generate self-signed certificate if it does not exist or will expire soon
if [ ! -f "${CERT_DIR}"/self.crt ] || ! openssl x509 -checkend 604800 -noout -in "${CERT_DIR}"/self.crt; then
	MUST_RESTART_KRESD=true
	(cd "${CERT_DIR}" \
		&& rm -f self.csr self.crt \
		&& openssl req -new -key self.key -out self.csr -subj '/CN=knot-resolver' \
		&& openssl req -x509 -days 90 -key self.key -in self.csr -out self.crt \
		&& chown root:knot-resolver self.csr self.crt \
		&& chmod 644 self.csr self.crt \
	)
fi

# Restart Knot Resolver if it is running
if [ "${MUST_RESTART_KRESD}" = true ] && supervisorctl-is-state kresd RUNNING; then
	supervisorctl restart kresd
fi
