#!/bin/sh

set -eu

GEOIPDB_DIR='/var/lib/knot-resolver/'
GEOIPDB_URL='https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz'
GEOIPDB_FILE="${GEOIPDB_DIR}/geoip.mmdb"
GEOIPDB_FILE_TMP=$(mktemp)
MUST_RESTART_KRESD=false

cleanup() { rm -f "${GEOIPDB_FILE_TMP}"; }
trap cleanup EXIT

curl -fsSL "${GEOIPDB_URL}" | gzip -d > "${GEOIPDB_FILE_TMP}"

if ! cmp --silent "${GEOIPDB_FILE_TMP}" "${GEOIPDB_FILE}"; then
	MUST_RESTART_KRESD=true
	mv -f "${GEOIPDB_FILE_TMP}" "${GEOIPDB_FILE}"
fi

# Restart Knot Resolver if it is running
if [ "${MUST_RESTART_KRESD}" = true ] && supervisorctl-is-state kresd RUNNING; then
	supervisorctl restart kresd
fi
