#!/bin/sh

set -eu

BLACKLIST='/var/lib/knot-resolver/blacklist.rpz'

# Generate blacklist zone
hblock \
		--quiet \
		--output "${BLACKLIST}" \
		--header "$(cat <<-'EOF'
			$TTL 2h
			@ IN SOA localhost. root.localhost. (1 6h 1h 1w 2h)
			  IN NS  localhost.
		EOF
		)" \
		--footer '' \
		--template '\1 CNAME .' \
		--comment ';'

# Restart Knot Resolver if it is running
if supervisorctl-is-state kresd RUNNING; then
	supervisorctl restart kresd
fi
