#!/bin/sh

set -eu

GEOIPDB_DIR='/var/lib/knot-resolver/'
GEOIPDB_FILE="${GEOIPDB_DIR}/geoip.mmdb"
GEOIPDB_FILE_TMP=$(mktemp)

cleanup() { rm -f "${GEOIPDB_FILE_TMP}"; }
trap cleanup EXIT

if [ -z "${GEOIPDB_URL-}" ]; then
	GEOIPDB_URL='https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz'
fi

# Download GeoIP database
curl -fL "${GEOIPDB_URL}" | gzip -d > "${GEOIPDB_FILE_TMP}"

# Replace GeoIP database if it differs
if ! cmp --silent "${GEOIPDB_FILE_TMP}" "${GEOIPDB_FILE}"; then
	mv -f "${GEOIPDB_FILE_TMP}" "${GEOIPDB_FILE}"
	# Restart Knot Resolver if it is running
	if supervisorctl-is-state kresd RUNNING; then
		supervisorctl restart kresd
	fi
fi
