#!/bin/sh

set -eu

cd "${KRESD_CACHE_DIR:?}"

# Wait until "data.mdb" exists before starting the garbage collector
until [ -e "${PWD:?}"/data.mdb ]; do sleep 1; done

exec 2>&1
exec kres-cache-gc -c "${PWD:?}" -d 1000
