# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: "hblock-resolver"

# https://hub.docker.com/_/traefik
x-traefik-image: &traefik-image "docker.io/traefik:3.4"
# https://hub.docker.com/r/hectorm/hblock-resolver
x-hblock-resolver-image: &hblock-resolver-image "docker.io/hectorm/hblock-resolver:latest"

services:

  traefik:
    image: *traefik-image
    restart: "on-failure:3"
    hostname: "traefik"
    networks:
      - "hblock-resolver"
    ports:
      - "80:80/tcp" # HTTP.
      - "443:443/tcp" # HTTPS.
      - "443:443/udp" # HTTPS (QUIC).
      - "853:853/tcp" # DNS over TLS.
    volumes:
      - { type: "bind", source: "./config/traefik/traefik.yml", target: "/etc/traefik/traefik.yml", read_only: true }
      - { type: "bind", source: "./config/traefik/dynamic/", target: "/etc/traefik/dynamic/", read_only: true }
      - { type: "volume", source: "traefik-acme", target: "/etc/traefik/acme/" }
    environment:
      DOMAIN: "${DOMAIN:?}"
      TRAEFIK_BASIC_AUTH: "${TRAEFIK_BASIC_AUTH:-}"
      TRAEFIK_TLS_RESOLVER: "${TRAEFIK_TLS_RESOLVER:-}"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      start_period: "120s"
      start_interval: "5s"
      interval: "30s"
      timeout: "10s"
      retries: 2

  hblock-resolver:
    image: *hblock-resolver-image
    restart: "on-failure:3"
    hostname: "hblock-resolver"
    networks:
      - "hblock-resolver"
    ports:
      - "127.0.0.153:53:53/udp" # DNS over UDP.
      - "127.0.0.153:53:53/tcp" # DNS over TCP.
    volumes:
      - { type: "volume", source: "hblock-resolver-data", target: "/var/lib/knot-resolver/" }
    environment:
      KRESD_INSTANCE_NUMBER: "${KRESD_INSTANCE_NUMBER:-4}"

volumes:

  traefik-acme:

  hblock-resolver-data:

networks:

  hblock-resolver:
