# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Rebuild latest release"

on:
  schedule:
    - cron: "20 04 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  trigger-rebuild:
    name: "Trigger rebuild"
    runs-on: "ubuntu-latest"
    permissions:
      actions: "write"
      contents: "read"
    steps:
      - name: "Trigger rebuild"
        uses: "hectorm/ghaction-trigger-workflow@04c79e7a4e0c0b94bbcff3829f38359e34f1ea9e"
        with:
          workflow-id: "main.yml"
